#!/bin/bash
# name=ABS Ratings Updater
# description=Starts a temporary Python container to scrape Audible and Goodreads ratings <br>for Audiobookshelf and inserts them into the ABS comments field.
# arrayStarted=true

# ================= CONFIGURATION =================

# 1. Paths
SCRIPT_DIR="PATH_TO_abs_ratings.py"
SCRIPT_NAME="abs_ratings.py"

# 2. Audiobookshelf Connection
ABS_URL="http://<YOUR_SERVER_IP>:<PORT>"

# 3. Authentication
API_TOKEN="<YOUR_API_TOKEN_HERE>"

# 4. Target Libraries
LIBRARY_IDS="<LIBRARY_ID_1>,<LIBRARY_ID_2>"

# 5. Execution Settings
BATCH_SIZE=250
SLEEP_TIMER=10
REFRESH_DAYS=90
DRY_RUN=false

# 6. Log Settings
LOG_RETENTION_DAYS=14

# ================= END CONFIGURATION =================

LOG_DIR="${SCRIPT_DIR}/logs"
mkdir -p "$LOG_DIR"

echo "------------------------------------------------"
echo "Starting ABS Ratings Update (Docker Run Method)"
echo "Date: $(date)"
echo "------------------------------------------------"

# Clean up old logs (Keep last X days)
find "$LOG_DIR" -type f -name "*.log" -mtime +$LOG_RETENTION_DAYS -delete

# Remove old env file if exists
rm -f "$SCRIPT_DIR/last_run.env"

# Launch Docker
docker run --rm \
  -v "$SCRIPT_DIR:$SCRIPT_DIR" \
  -e ABS_URL="$ABS_URL" \
  -e API_TOKEN="$API_TOKEN" \
  -e LIBRARY_IDS="$LIBRARY_IDS" \
  -e BATCH_SIZE="$BATCH_SIZE" \
  -e SLEEP_TIMER="$SLEEP_TIMER" \
  -e REFRESH_DAYS="$REFRESH_DAYS" \
  -e DRY_RUN="$DRY_RUN" \
  python:3.11-slim \
  /bin/bash -c "pip install requests beautifulsoup4 lxml > /dev/null 2>&1 && python3 \"$SCRIPT_DIR/$SCRIPT_NAME\""

# ================= NOTIFICATION =================

# Load variables generated by Python script (stats, status, icons)
if [ -f "$SCRIPT_DIR/last_run.env" ]; then
    source "$SCRIPT_DIR/last_run.env"

    # Formatting separators (based on your snippet)
    SEP=" | "
    BIG_SEP=" || "

    # Construct Message
    # Format: [ HEADER ] | Duration: XX | Log: filename || DETAILS: ...
    FINAL_MSG="${ABS_HEADER}${SEP}Dauer: ${ABS_DURATION}${SEP}Log: ${ABS_LOG_FILE}${BIG_SEP}${ABS_REPORT_BODY}"

    # Send Notification
    /usr/local/emhttp/webGui/scripts/notify -e "ABS Ratings" -s "$ABS_SUBJECT" -d "$FINAL_MSG" -i "$ABS_ICON"

else
    echo "Error: No result environment file found. Python script might have crashed."
    /usr/local/emhttp/webGui/scripts/notify -e "ABS Ratings" -s "ABS Update: Kritischer Fehler ❌" -d "Das Python-Script konnte nicht korrekt beendet werden. Bitte Logs prüfen." -i "alert"
fi

echo "------------------------------------------------"
echo "Script finished."
echo "------------------------------------------------"
